---
name: Bruno Pinheiro de Oliveira
surname: ""
date: "`r format(Sys.time(), '%B %Y')`"
address: Peruíbe/SP - Brasil
phone: +55 11 983070201 
email: "bruno.lahunmen@gmail.com"
# www: alemdamedia.netlify.com
# twitter: mariecurie
# position: "Cientista de Dados"
github: bruno-po
linkedin: brunopinheirooliveira
docname: CV/Resume
aboutme: Data Scientist
output: #vitae::latexcv
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

```{r get_data, include=FALSE}
source('../scripts/data.R')
```

# Skills

```{r}
skills %>%
  group_by(category) %>%
  mutate(skill = paste(skill, collapse = ", ")) %>%
  ungroup %>%
  unique %>% 
  detailed_entries(why = skill, what = category)
```

# Experiência

```{r experience}
jobs %>% 
  detailed_entries(
    what = role,
    when = glue::glue("{start_date}--{end_date}"),
    with = company,
    where = where,
    why = details
    )
```


# Educação

```{r}
detailed_entries(education, 
                 when = glue::glue("{start_date}--{end_date}"),
                 what = degree,
                 where = loc,
                 with = uni)
```


__Capacitações__

```{r}
training %>% 
  detailed_entries(what = what, with = with, when = when, where = where)
```

```{r}
# Teaching
# teaching %>% 
#   detailed_entries(what = what, when = when, with = with, where = where, why = why)
```

# Publicações

```{r}
publications %>% 
  detailed_entries(
    what = author,
    when = year,
    with = title,
    where = journal
  )
```

# Outras atividades

```{r}
service %>% 
  detailed_entries(with = type, why = service)
```
